import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "@/components/layout/Header/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4 xl:p-4 bg-slate-200 `}>
        <Providers>
          <header>
            {<NavBar />}
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
